name: ci-javacdtest
'on':
  push:
    branches:
      - main
    paths:
      - '**/javacdtest/**'
env:
  DOCKER_FILE_PATH: ./javacdtest/Dockerfile
  DOCKER_BUILD_CONTEXT: javacdtest
  CONTAINER_NAME: java-pipeline-test
  REPOSITORY_NAME: java-pipeline-test
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CR_LOGIN_SERVER }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      - name: Build, test and push image to container registry
        run: |-
          docker build ${{ env.DOCKER_BUILD_CONTEXT }} -f ${{ env.DOCKER_FILE_PATH }} -t ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:${{ github.run_number }}
          docker push ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:${{ github.run_number }}
      - name: unittest
        uses: dorny/test-reporter@v1
        with:
          name: test-results
          path: '**/*.trx'
          reporter: dotnet-trx
      - name: build
